name: go-test
on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  gotest:
    name: go test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: Test
        run: go test -covermode atomic -coverpkg=./... -coverprofile=covprofile ./...
      - name: Convert coverage profile
        run: |
          go install github.com/jandelgado/gcov2lcov@latest
          gcov2lcov -infile=covprofile -outfile=coverage.lcov
      - name: Coveralls
        uses: coverallsapp/github-action@v2